CREATE TABLE IF NOT EXISTS champions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    lore TEXT,
    image_url VARCHAR(255)
);

INSERT INTO champions (name, role, lore, image_url) VALUES
    ('Jinx', 'Atirador', 'Uma criminosa impulsiva e maníaca de Zaun, Jinx vive para disseminar o caos sem se preocupar com as consequências. Com um arsenal de armas mortais, ela detona as explosões mais altas e mais luminosas para deixar um rastro de destruição e pânico por onde passa. Jinx abomina o tédio e deixa alegremente sua marca caótica de pandemônio aonde quer que vá.', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jinx_0.jpg'),
    ('Vi', 'Lutador', 'Antiga criminosa das ruas violentas de Zaun, Vi é uma mulher temível, impulsiva e explosiva que tem muito pouco respeito por autoridades. Após ter crescido completamente só, Vi desenvolveu instintos de sobrevivência extremamente certeiros e um senso de humor extremamente ácido. Agora trabalhando com os Vigias de Piltover para manter a paz, ela porta poderosas manoplas hextec capazes de esmagar paredes e suspeitos com a mesma facilidade.', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vi_0.jpg'),
    ('Ekko', 'Assassino', 'Um prodígio das ruas violentas de Zaun, Ekko manipula o tempo para reverter qualquer situação a seu favor. Usando sua própria invenção, o Revo-Z, ele explora as possíveis bifurcações da realidade para criar o momento perfeito. Embora valorize muito sua liberdade, quando algo ameaça seus amigos, ele não mede esforços para defendê-los. Para meros observadores, Ekko parece conseguir o impossível sempre de primeira.', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ekko_0.jpg'),
    ('Caitlyn', 'Atirador', 'Conhecida como sua melhor pacificadora, Caitlyn também é a melhor escolha de Piltover para livrar a cidade de seus elementos criminosos elusivos. É comum que ela faça dupla com Vi, agindo como um contraponto de calmaria para a natureza impetuosa de sua parceira. Mesmo carregando um rifle hextec único, a arma mais poderosa de Caitlyn é seu intelecto superior, que permite que ela prepare elaboradas armadilhas para qualquer fora da lei tolo o suficiente para operar na Cidade do Progresso.', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Caitlyn_0.jpg'),
    ('Jayce', 'Lutador', 'Jayce é um brilhante inventor que dedicou sua vida a defender Piltover e sua implacável busca pelo progresso. Com seu martelo hextech transformador em mãos, Jayce usa sua força, coragem e considerável inteligência para proteger sua cidade natal. Embora seja aclamado pela cidade como herói, ele não gosta muito da atenção que o heroísmo traz. Mesmo assim, o coração de Jayce está no lugar certo e até aqueles que invejam suas habilidades naturais são gratos à forma como ele protege a Cidade do Progresso.', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jayce_0.jpg'),
    ('Viktor', 'Mago', 'Viktor, o arauto de uma nova era de tecnologia, devotou sua vida ao avanço da humanidade. Um idealista que busca elevar o povo de Zaun a um novo nível de compreensão, ele acredita que somente ao aceitar a evolução gloriosa da tecnologia será possível que a humanidade alcance seu verdadeiro potencial. Com um corpo melhorado por aço e ciência, Viktor é zeloso na sua busca por este brilhante futuro.', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Viktor_0.jpg'),
    ('Heimerdinger', 'Mago', 'Um cientista brilhante, mesmo que excêntrico, o Professor Cecil B. Heimerdinger é um dos inventores mais inovadores e estimados que Piltover já conheceu. Incansável em seu trabalho ao ponto da obsessão neurótica, ele busca responder as questões mais impenetráveis do universo. Apesar de suas teorias frequentemente parecerem obscuras e esotéricas, Heimerdinger produziu algumas das máquinas mais miraculosas, sem mencionar letais, de Piltover e ajusta constantemente suas invenções para torná-las ainda mais eficientes.', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Heimerdinger_0.jpg'),
    ('Aatrox', 'Lutador', 'Aatrox, a Espada Darkin, é um ser imortal e sedento de sangue, uma lenda entre os guerreiros de Runeterra. Ele personifica a guerra e a destruição, buscando vingança contra aqueles que o aprisionaram. Com sua espada devastadora, Aatrox inflige dor e desespero em seus inimigos, consumindo suas almas para se fortalecer. Sua presença inspira terror e reverência, enquanto ele continua sua busca por redenção através do caos. Aatrox é uma força imparável que desafia até mesmo os deuses, moldando o destino com sua fúria inextinguível.', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aatrox_0.jpg'),
    ('Ryze', 'Mago', 'Considerado pela grande maioria como o mago mais habilidoso de Runeterra, Ryze é um arquimago ancião e amargo que carrega um enorme peso. Dotado de um enorme poder arcano e de uma notável estrutura física, ele busca incansavelmente pelas Runas Globais, que são fragmentos de magia pura que um dia criaram o mundo a partir do nada. Ele deve recuperar esses artefatos antes que eles caiam em mãos erradas, pois Ryze conhece bem os horrores que eles podem infligir em Runeterra.', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ryze_0.jpg'),
    ('Sylas', 'Assassino', 'Sylas, o Abjulgado, é um revolucionário de Demacia, temido por sua habilidade de roubar e utilizar magia. Ele lidera uma rebelião contra o regime opressivo, lutando pela liberdade dos oprimidos. Com sua capacidade de manipular e controlar magia, Sylas desafia as convenções e ameaça o status quo de Demacia. Sua determinação em quebrar as correntes da tirania o torna uma figura icônica entre os desfavorecidos. Sylas é uma ameaça aos poderes estabelecidos, desafiando-os com sua vontade implacável de mudança.', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sylas_0.jpg'),
    ('Lux', 'Mago', 'Luxanna, a Dama da Luz, é uma maga em Demacia, conhecida por sua habilidade excepcional e devoção à justiça. Incansável em sua busca pelo bem, ela utiliza sua magia para proteger os inocentes e combater as trevas. Apesar de sua natureza gentil, Lux é uma oponente formidável, capaz de lançar feitiços poderosos com precisão impecável. Sua determinação em defender sua terra natal a torna uma das magas mais respeitadas de toda Runeterra.', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lux_17.jpg'),
    ('Katarina', 'Assasino', 'Katarina, a Lâmina Sinistra de Noxus, é uma assassina temida por sua agilidade e precisão letal. Com sua destreza incomparável, ela deixa um rastro de destruição por onde passa, antecipando os movimentos de seus inimigos com facilidade. Sua reputação sombria é equilibrada por um código de honra próprio, e sua lealdade à sua família e pátria é inabalável. Katarina é uma força formidável nos campos de batalha de Runeterra, sua determinação incansável a torna uma das assassinas mais respeitadas e temidas em todo o continente.', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Katarina_0.jpg');